FROM ubuntu:24.04

ENV container=docker
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    systemd \
    systemd-sysv \
    sudo \
    curl \
    ca-certificates \
    jq \
    iproute2 \
    iptables \
    procps \
    kmod \
    iputils-ping \
    net-tools \
    dnsutils \
    open-iscsi \
    nfs-kernel-server \
    file \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY . /workspace

CMD ["bash"]
